name: Medkit
favicon: null
layout_spectrum: 0.6197509767953306
typography_spectrum: 0.8855573139153421
title: Ensuring Site Safety Stays First
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcbce'
    - '#005500'
    - '#838377'
    - '#5cff89'
    - '#00cd17'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
