name: Medkit
favicon: null
layout_spectrum: 0.6197509767953306
typography_spectrum: 0.8855573139153421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7150758071802557
  lightness: 0.7691150538157672
  saturation: 0.03684757091104984
  rhythmicContrast: 0.2952325630467385
purpose: []
